### ISSUE TITLE
Références

### ISSUE THREAD

**Issue by ASionville** [djbouns/AQUABOUNS-V2.0#1]
Bonjour,

Dans la documentation, je vois qu'il y a besoin d'un flotteur, est ce que vous auriez une référence à donner ?

De la même manière, auriez-vous une référence pour le relais DIN ?

Merci d'avance

**Comment by djbouns** [comment]
Bonsoir, oui, https://amzn.to/3u6YL4T

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Aubin Sionville ***@***.***>
Envoyé : Saturday, May 1, 2021 11:02:28 PM
À : djbouns/AQUABOUNS-V2.0 ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [djbouns/AQUABOUNS-V2.0] Référence Flotteur (#1)


Bonjour,

Dans la documentation, je vois qu'il y a besoin d'un flotteur, est ce que vous auriez une référence à donner ?

Merci d'avance

**Comment by ASionville** [comment]
Merci pour la référence des flotteurs

A quoi sert le deuxième lien ?

**Comment by djbouns** [comment]
Le quel ?

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Aubin Sionville ***@***.***>
Envoyé : Saturday, May 1, 2021 11:19:39 PM
À : djbouns/AQUABOUNS-V2.0 ***@***.***>
Cc : djbouns ***@***.***>; Comment ***@***.***>
Objet : Re: [djbouns/AQUABOUNS-V2.0] Références (#1)


Merci pour la référence des flotteurs

A quoi sert le deuxième lien ?

**Comment by ASionville** [comment]
![image](https://user-images.githubusercontent.com/57773476/116795256-fdee3400-aad3-11eb-8320-f625931eae8b.png)
Celui-là

**Comment by ASionville** [comment]
Aussi, auriez-vous une référence pour le relais DIN s'il vous plaît ?

**Comment by djbouns** [comment]
Oui, https://amzn.to/3eaSUpW

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Aubin Sionville ***@***.***>
Envoyé : Saturday, May 1, 2021 11:38:44 PM
À : djbouns/AQUABOUNS-V2.0 ***@***.***>
Cc : djbouns ***@***.***>; Comment ***@***.***>
Objet : Re: [djbouns/AQUABOUNS-V2.0] Références (#1)


Aussi, auriez-vous une référence pour le relais DIN s'il vous plaît ?

**Comment by ASionville** [comment]
Merci !!

**Comment by ASionville** [comment]
Pour tous ceux qui voudraient avoir la liste des pièces :

https://docs.google.com/spreadsheets/d/1T9jjPReNh7rsR9bEjEVjJaScgoRw9wAk_IOGPQ7D5x8/edit?usp=sharing

**Comment by ASionville** [comment]
Pour tous ceux qui voudraient avoir la liste des pièces :

https://docs.google.com/spreadsheets/d/1T9jjPReNh7rsR9bEjEVjJaScgoRw9wAk_IOGPQ7D5x8/edit?usp=sharing

**Comment by djbouns** [comment]
Merci, il yna deja une liste de pieces disponible sur le groupe facebook

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Aubin Sionville ***@***.***>
Envoyé : Saturday, May 1, 2021 11:53:12 PM
À : djbouns/AQUABOUNS-V2.0 ***@***.***>
Cc : djbouns ***@***.***>; Comment ***@***.***>
Objet : Re: [djbouns/AQUABOUNS-V2.0] Références (#1)


Pour tous ceux qui voudraient avoir la liste des pièces :

https://docs.google.com/spreadsheets/d/1T9jjPReNh7rsR9bEjEVjJaScgoRw9wAk_IOGPQ7D5x8/edit?usp=sharing

**Comment by djbouns** [comment]
De rien.
Bonne soiree


Tout est mis a votre disposition gratuitement et permet d'avoir un automate qui aurais pu vous coûter ~1000€ dans le commerce.
Soutenez le projet pour qu'il continue d’évoluer et d’être mis à disposition gratuitement en faisant un don PAYPAL ;)
https://paypal.me/pools/c/88NxY14ZuS

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Aubin Sionville ***@***.***>
Envoyé : Saturday, May 1, 2021 11:52:38 PM
À : djbouns/AQUABOUNS-V2.0 ***@***.***>
Cc : djbouns ***@***.***>; Comment ***@***.***>
Objet : Re: [djbouns/AQUABOUNS-V2.0] Références (#1)


Merci !!

**Comment by ASionville** [comment]
Effectivement je n'avait pas vu...

Merci beaucoup à toi, malheureusement, je suis étudiant (l'aquarium n'est pas à moi), donc je n'ai pas les moyens de faire des dons.
